name: Debricked Vulnerability Scan
author: Debricked
description: Integrates with Debricked to automatically scan your dependencies for vulnerabilities and license risks
runs:
  using: composite
  steps:
    - uses: debricked/actions/cache@v4
    - uses: debricked/actions/docker-scan@v4
branding:
  color: purple
  icon: search
