name: Debricked Callgraph Generation
author: Debricked
description: Generates a callgraph to be used to figure out if vulnerable symbols are actually being called in the code
runs:
  using: composite
  steps:
    - name: Install Debricked CLI
      run: curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
      shell: bash
    - name: Debricked Resolve
      run: ./debricked callgraph
      shell: bash
branding:
  color: purple
  icon: search
