name: Debricked Callgraph Generation
author: Debricked
description: Generates a callgraph to be used to figure out if vulnerable symbols are actually being called in the code
runs:
  using: composite
  steps:
    - name: Install Debricked CLI
      uses: debricked/actions/non-docker@v4
    - name: Debricked Resolve
      run: ./debricked callgraph
      shell: bash
branding:
  color: purple
  icon: search
