name: Debricked Fingerprint
author: Debricked
description: Generates a debricked.fingerprints.txt containing fingerprints of files to be used to detect Open Source dependencies not included in manifest files.
runs:
  using: composite
  steps:
    - name: Install Debricked CLI
      uses: debricked/actions/non-docker@v3
    - name: Debricked Fingerprint
      run: ./debricked fingerprint
      shell: bash
branding:
  color: purple
  icon: search
