name: Debricked Vulnerability Scan
author: Debricked
description: Integrates with Debricked to automatically scan your dependencies for vulnerabilities and license risks
runs:
  using: composite
  steps:
    - name: Install Debricked CLI
      uses: debricked/actions/non-docker@v3
    - name: Debricked Scan
      run: ./debricked scan
      shell: bash
branding:
  color: purple
  icon: search
