name: Debricked Vulnerability Resolve
author: Debricked
description: Integrates with Debricked to generate the appropriate Debricked lock files from found eligible manifest files, that do not have related lock files
runs:
  using: composite
  steps:
    - name: Install Debricked CLI
      uses: debricked/actions/non-docker@v3
    - name: Debricked Resolve
      run: ./debricked resolve
      shell: bash
branding:
  color: purple
  icon: search
