name: Debricked CLI installation
author: Debricked
description: Installs the Debricked CLI
runs:
  using: composite
  steps:
    - name: Install Debricked CLI
      run: |
        # Convert GitHub's RUNNER_ARCH naming convention to match the ones we use for releases
        if [ "${RUNNER_ARCH}" == "X64" ]; then RUNNER_ARCH=x86_64; fi
        if [ "${RUNNER_ARCH}" == "X86" ]; then RUNNER_ARCH=i386; fi
        BIN_NAME=debricked
        if [ "${RUNNER_OS}" == "Windows" ]; then BIN_NAME=debricked.exe; fi
        echo "https://github.com/debricked/cli/releases/download/release-v2/cli_${RUNNER_OS}_${RUNNER_ARCH}.tar.gz"
        curl -L "https://github.com/debricked/cli/releases/download/release-v2/cli_${RUNNER_OS}_${RUNNER_ARCH}.tar.gz" | tar -xz "${BIN_NAME}"
      shell: bash
branding:
  color: purple
  icon: search
